### ISSUE TITLE
Request to target Java 1.8+

### ISSUE THREAD

**Issue by ZhongRuoyu** [apetresc/hexgui#3]
Hi! [Homebrew](https://github.com/Homebrew/brew) maintainer here. While packaging OpenJDK 20 for Homebrew, we noticed that the latest release of HexGui is still targeting Java 1.7. Support for Java 1.7 [has already ended](https://www.oracle.com/java/technologies/java-se-support-roadmap.html), and JDK 20 [no longer supports Java 1.7 targets](https://jdk.java.net/20/release-notes#JDK-8173605). As a result, HexGui can no longer be built with the newest JDK. Would you consider bumping the target Java version to 1.8? Thanks!

**Comment by apetresc** [comment]
Hey @ZhongRuoyu - absolutely, I'll put this on my to-do list for this weekend!

**Comment by apetresc** [comment]
@ZhongRuoyu Release v0.9.4 just posted with 1.8 compatibility and another nice quality-of-life improvement.

Should I open a PR against brew or is it easier for you to push that?

**Comment by ZhongRuoyu** [comment]
Thanks @apetresc! I opened https://github.com/Homebrew/homebrew-core/pull/126649.

**Comment by ZhongRuoyu** [comment]
And it's very easy to open one: all I did was `brew bump-formula-pr --strict hexgui --version=0.9.4`.

**Comment by apetresc** [comment]
Oh I know, I've done many dozens of those, I just figured as an org member you might have ways of just pushing it through without waiting for a review or something :)

Thanks so much! And thanks for putting in the temporary workaround until I got to this. Cheers!

**Comment by ZhongRuoyu** [comment]
> I just figured as an org member you might have ways of just pushing it through without waiting for a review or something

Maintainers' work is also done through PRs; everything needs to be tested by CI and get approved by another maintainer.

Cheers!
